# Generated by Django 3.2.4 on 2024-02-16 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_product_product_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product_file',
        ),
    ]
